# Basic `dependabot.yml` file

version: 2
updates:
  # Enable version updates for pnpm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the pnpm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
