[build]
  command = "corepack enable && pnpm i --frozen-lockfile && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "10"
  NPM_FLAGS = "--include=dev"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    thresholds = { performance = 75, accessibility = 85, "best-practices" = 80, seo = 85, pwa = 70 }
    fail_deploy_on_score_thresholds = false  # don’t block deploy, just report

    [[plugins.inputs.audits]]
      url = "/"
      output_path = "reports/lighthouse-landing-desktop.html"
      preset = "desktop"

    [[plugins.inputs.audits]]
      url = "/"
      output_path = "reports/lighthouse-landing-mobile.html"
      preset = "mobile"

    [[plugins.inputs.audits]]
      url = "/join"
      output_path = "reports/lighthouse-join-desktop.html"
      preset = "desktop"

    [[plugins.inputs.audits]]
      url = "/join"
      output_path = "reports/lighthouse-join-mobile.html"
      preset = "mobile"

    [[plugins.inputs.audits]]
      url = "/create-session"
      output_path = "reports/lighthouse-create-session-desktop.html"
      preset = "desktop"

    [[plugins.inputs.audits]]
      url = "/create-session"
      output_path = "reports/lighthouse-create-session-mobile.html"
      preset = "mobile"

    [[plugins.inputs.audits]]
      url = "/api-status"
      output_path = "reports/lighthouse-api-status.html"
      preset = "desktop"

    [[plugins.inputs.audits]]
      url = "/"
      output_path = "reports/lighthouse-landing-performance.html"
      preset = "perf"

    [[plugins.inputs.audits]]
      url = "/join"
      output_path = "reports/lighthouse-join-performance.html"
      preset = "perf"

# Optional post-build summary
[[build.lifecycle]]
  onSuccess = """
  echo '=== Lighthouse reports generated in /reports ==='
  ls -lh reports
  """

[context.production]
  publish = "dist"
  artifactPath = ["dist", "reports"]

[dev]
  framework = "vite"
  command = "pnpm run dev"
  port = 3000
  targetPort = 5173
  autoLaunch = false
