# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [ minimal, main, advanced ]
  pull_request:
    branches: [ minimal, main, advanced ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm run test -- --run
        env:
          SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
          SUPABASE_ANON_KEY:     ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_JWT_SECRET:   ${{ secrets.SUPABASE_JWT_SECRET }}
          DAILY_API_KEY:         ${{ secrets.DAILY_API_KEY }}
      - name: Build
        run: npm run build
        env:
          VITE_SUPABASE_DATABASE_URL: ${{ secrets.VITE_SUPABASE_DATABASE_URL }}
          VITE_SUPABASE_ANON_KEY:     ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_DAILY_DOMAIN:          ${{ secrets.VITE_DAILY_DOMAIN }}
