name: CI
on:
  push:
    branches: [ minimal, main, advanced ]
  pull_request:

    branches: [ minimal, main, advanced ]

env:                      # shared across all jobs and steps
  # ----- Front-end (Vite) -----
  VITE_SUPABASE_DATABASE_URL: ${{ secrets.VITE_SUPABASE_DATABASE_URL }}
  VITE_SUPABASE_ANON_KEY:     ${{ secrets.VITE_SUPABASE_ANON_KEY }}
  VITE_DAILY_DOMAIN:          ${{ secrets.VITE_DAILY_DOMAIN }}
  # ----- Serverless (Netlify Functions) -----
  SUPABASE_DATABASE_URL:      ${{ secrets.SUPABASE_DATABASE_URL }}
  SUPABASE_ANON_KEY:          ${{ secrets.SUPABASE_ANON_KEY }}
  SUPABASE_SERVICE_ROLE_KEY:  ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  SUPABASE_JWT_SECRET:        ${{ secrets.SUPABASE_JWT_SECRET }}
  DAILY_API_KEY:              ${{ secrets.DAILY_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest    # Speed up with pnpm store cache
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
          
      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Unit + integration tests
        run: pnpm run test -- --run

      - name: Build
        run: pnpm run build

