# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [ minimal, main, advanced ]
  pull_request:
    branches: [ minimal, main, advanced ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with: 
          version: 8            
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: pnpm test
        run: npm run test -- --run
        env:
          SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
          SUPABASE_ANON_KEY:     ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_JWT_SECRET:   ${{ secrets.SUPABASE_JWT_SECRET }}
          DAILY_API_KEY:         ${{ secrets.DAILY_API_KEY }}
      - name: Build
        run: pnpm build
        env:
          VITE_SUPABASE_DATABASE_URL: ${{ secrets.VITE_SUPABASE_DATABASE_URL }}
          VITE_SUPABASE_ANON_KEY:     ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_DAILY_DOMAIN:          ${{ secrets.VITE_DAILY_DOMAIN }}
