name: Format
on:
  workflow_run:
    workflows: ["Lint"] # ← name of the workflow that contains your Prettier check
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          # version removed to avoid mismatch
          run_install: false
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm exec prettier --check .

      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "style(prettier): auto-format after failed lint run"
          branch: ${{ github.event.workflow_run.head_branch }}
