name: Format
on:
  workflow_run:
    workflows: ["Lint"] # ← name of the workflow that contains your Prettier check
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          # version removed to avoid mismatch
          run_install: false
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm exec prettier --check .

      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
        with:
          commit_message: "style(prettier): auto-format after failed lint run"
          branch: ${{ github.event.workflow_run.head_branch }}
