name: Lint
on:
  pull_request:
    branches: [ minimal, main, advanced ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm run lint
