name: Lint
on:
  pull_request:
    branches: [minimal, main, advanced]

permissions:
  contents: read

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      # with block removed to avoid empty block error
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm run lint
